### ISSUE TITLE
Add RSpec howto to enable capybara-firebug

### ISSUE THREAD

**Issue by ticketevo** [jfirebaugh/capybara-firebug#11]
In order to use the gem, we had to add the following to our spec_helper.rb.

Perhaps this should be added to the readme documentation?

``` ruby

RSpec.configure do |config|
  config.before(:each, firebug: true) do
    Capybara.current_driver = :selenium_with_firebug
  end
end

```

**Comment by jfirebaugh** [comment]
Ah, this is the "using Capybara in RSpec without Cucumber" case.

I think we should add your code as a default in capybara/firebug.rb, within `if defined?(RSpec)` (analogous to the existing `if defined?(Cucumber::RbSupport)` block). Care to submit a PR?

**Comment by ticketevo** [comment]
Sure thing.
