### ISSUE TITLE
Firebug 1.11

### ISSUE THREAD

**Issue by enricostano** [jfirebaugh/capybara-firebug#16]
Hi,

it doesn't work with Firebug 1.11, Firebug simply doesn't show up.

what I could try?

thanks!

**Comment by jfirebaugh** [comment]
Firebug 1.11 is still an alpha release. Please use 1.10.

**Comment by jfirebaugh** [comment]
Never mind, they just haven't updated their downloads page.

**Comment by jfirebaugh** [comment]
capybara-firebug 1.3.0 has firebug 1.11 bundled.
