### ISSUE TITLE
In acceptance testing

### ISSUE THREAD

**Issue by sadiksha** [jfirebaugh/capybara-firebug#4]
Is there anyway I can use firebug on selenium-webdriver with acceptance testing? I am using steak for acceptance testing.

**Comment by jfirebaugh** [comment]
You mean without a capybara dependency? There's not a way to do this currently. You probably just want to copy and paste the [relevant lines](https://github.com/jfirebaugh/capybara-firebug/blob/master/lib/capybara/firebug.rb#L1-30).
