### ISSUE TITLE
no such file to load -- ruby-debug (LoadError)

### ISSUE THREAD

**Issue by artemave** [jfirebaugh/capybara-firebug#7]
`Then stop and let me debug                            # capybara-firebug-0.0.7/lib/capybara/firebug.rb:43
      no such file to load -- ruby-debug (LoadError)`

I think specifying dependencies in .gemspec will fix this

**Comment by silviorelli** [comment]
It depends on the ruby-debug gem, this should be specified in the gemspec as dependency.
BTW ruby-debug gem seems to me not compatible with Ruby 1.9.2, so I tried use a simple "sleep step" instead of the provided "stop and let me debug" step.

``` ruby
Given /^I sleep (\d+) seconds$/ do |sec|
  sleep sec.to_i
end
```

**Comment by artemave** [comment]
Use ruby-debug19 for 1.9.X

**Comment by silviorelli** [comment]
Awesome, works

**Comment by silviorelli** [comment]
I would write a patch but I don't know how to specify a different dependecy in the gemspec depending on the Ruby version!

**Comment by artemave** [comment]
Use RUBY_VERSION constant

**Comment by jfirebaugh** [comment]
Unfortunately there is no clean way to specify a dependency in the gemspec that varies depending on the Ruby version. So you will need to add it to your Gemspec. I've added documentation to this effect to the README.
